version: "2"
x-redash-service: &redash-service
  image: redash/redash:8.0.0.b32245
  depends_on:
    - postgres
    - redis
  env_file: env
  restart: always
services:
  server:
    <<: *redash-service
    command: server
    ports:
      - "5000:5000"
    environment:
      REDASH_WEB_WORKERS: 4
    links:
      - postgres
      - bipg_container
  scheduler:
    <<: *redash-service
    command: scheduler
    environment:
      QUEUES: "celery"
      WORKERS_COUNT: 1
    links:
      - postgres
      - bipg_container
  scheduled_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "scheduled_queries,schemas"
      WORKERS_COUNT: 1
    links:
      - postgres
      - bipg_container
  adhoc_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 2
    links:
      - postgres
      - bipg_container
  redis:
    image: redis:5.0-alpine
    restart: always
    links:
      - postgres
      - bipg_container
  nginx:
    image: redash/nginx:latest
    ports:
      - "3000:80"
    depends_on:
      - server
    links:
      - server:redash
    restart: always
  postgres:
    image: postgres:9.6-alpine
    env_file: env
    ports:
      - "5432:5432"
    volumes:
      - ./redash/postgres:/var/lib/postgresql/data
    restart: always
  bipg_container:
    container_name: bipg_container
    #image: h20/bi-postgres
    build: postgres/
    environment:
      POSTGRES_USER: shoc
      POSTGRES_PASSWORD: JustKeepSwimming
      POSTGRES_DB: test_db
    ports:
      - "5431:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    restart: always
  bipg_admin:
    container_name: bipg_admin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: shoc@shoc.us
      PGADMIN_DEFAULT_PASSWORD: JustKeepSwimming
    links:
      - postgres
      - bipg_container
    ports:
      - "3031:80"

